// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Config():Promise<Record<string, any>>;

export function Greet(arg1:string):Promise<string>;

export function NewGame(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<Array<number>>;

export function SelectDataDirectory():Promise<string>;
