// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActiveGame() {
  return window['go']['main']['App']['ActiveGame']();
}

export function Config() {
  return window['go']['main']['App']['Config']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function NewGame(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['NewGame'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SelectDataDirectory() {
  return window['go']['main']['App']['SelectDataDirectory']();
}
