// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ipc} from '../models';
import {main} from '../models';

export function ActiveGame():Promise<ipc.GameDocument>;

export function Config():Promise<main.Config>;

export function Greet(arg1:string):Promise<string>;

export function NewGame(arg1:string,arg2:string,arg3:string,arg4:ipc.ChallengeRule,arg5:string,arg6:string):Promise<ipc.GameDocument>;
